In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\danish\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [1]:
import numpy as np

In [3]:
l1 = [4,6,9,54,34]

In [5]:
type(l1)

list

In [6]:
np.array(l1)

array([ 4,  6,  9, 54, 34])

In [7]:
arr1 = np.array(l1)

In [8]:
type(arr1)

numpy.ndarray

In [8]:
l2 = [4.6, 78.0, 7 ,65]
np.array(l2)

array([ 4.6, 78. ,  7. , 65. ])

In [11]:
arr2 = np.array(l2)

NameError: name 'l2' is not defined

In [11]:
arr1.dtype

dtype('int32')

In [12]:
arry2d= np.arange(1,10).reshape((3,3))

In [12]:
arry2d.shape

NameError: name 'arry2d' is not defined

In [14]:
arry2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arry2d.ndim

2

In [21]:
arry2d.size

9

In [22]:
len(arry2d)

3

In [23]:
arry2d.dtype

dtype('int32')

In [24]:
np.zeros((4,3), dtype= 'int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
np.zeros((4,3), dtype=complex)

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [29]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

## NUMPY OPERATION

In [33]:
arr1.shape

(5,)

In [32]:
arr1*5

array([ 20,  30,  45, 270, 170])

In [34]:
arr1 % 2 == 0

array([ True,  True, False,  True,  True])

In [35]:
arr1

array([ 4,  6,  9, 54, 34])

## create a 2D array of 20 elements.
## convert [(1,2,3,4),(5,6,7,8), (9,20,67,54)] in a 2D array of 3,4
## 

In [13]:
arry2d= np.arange(1,21).reshape((4,5))

In [14]:
arry2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
array1 = [(1, 2, 3, 4),(5, 6, 7, 8), (9, 10, 11, 12)]

In [16]:
y= np.array(array1)

In [17]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
np.arange(1,13).reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
np.arange(1,13).reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## QUESTION3: Create an array from 10, 50 with a step of 5 and convert to 3 possible array shape combinations.

In [20]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
x = np.arange(10,50,5).reshape(4,2 )

In [22]:
x

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [24]:
x = np.arange(10,50,5).reshape(2,2,2 )

In [25]:
x

array([[[10, 15],
        [20, 25]],

       [[30, 35],
        [40, 45]]])

In [26]:
mat3 = np.arange(5,50,5).reshape((3,3))

In [27]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
bool_arr = mat3 % 10 == 0

In [29]:
bool_arr

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [30]:
mat3[bool_arr]

array([10, 20, 30, 40])

In [31]:
mat3 * 2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [35]:
mat4 = np.arange(1,10).reshape((3,3))

In [36]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
mat3 + mat4

array([[ 6, 12, 18],
       [24, 30, 36],
       [42, 48, 54]])

## MATRICX MULTIPLICATION

In [37]:
mat3 @ mat4

array([[150, 180, 210],
       [330, 405, 480],
       [510, 630, 750]])

In [46]:
ultimatrix = np.arange(25).reshape((5,5))

In [47]:
ultimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
ultimatrix[2 ]

array([10, 11, 12, 13, 14])

In [51]:
ultimatrix[2 :5,2 ]

array([12, 17, 22])

In [52]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
mat5 = np.arange(1,7).reshape((2,3))

In [55]:
mat5

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
np.arange(10,18).reshape(2,2,2)

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

In [3]:
mat3= np.arange(5,50,5).reshape((3,3))

In [4]:
mat3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
bool_arr = mat3 % 10 == 0

In [6]:
bool_arr

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [7]:
mat3[bool_arr]

array([10, 20, 30, 40])

In [8]:
mat3 * 2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
mat4 = np.arange(1,10).reshape((3,3))

In [10]:
mat4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mat4+mat3

array([[ 6, 12, 18],
       [24, 30, 36],
       [42, 48, 54]])

In [12]:
mat3 * mat4

array([[  5,  20,  45],
       [ 80, 125, 180],
       [245, 320, 405]])

## MATRIX MULTIPICATION

In [13]:
mat3 @ mat4

array([[150, 180, 210],
       [330, 405, 480],
       [510, 630, 750]])

In [14]:
mat3.max()

45

In [15]:
mat4.min()

1

In [16]:
mat3.sum()

225

In [17]:
mat4.mean()

5.0

In [19]:
np.random.random((4,4))

array([[0.51693518, 0.28030058, 0.31824565, 0.99317472],
       [0.14843431, 0.31730083, 0.51274646, 0.11969966],
       [0.8818464 , 0.27628868, 0.79362563, 0.26490616],
       [0.77892616, 0.20553183, 0.16977085, 0.56780569]])

In [21]:
np.random.randint(10,20, (4,4))

array([[16, 13, 16, 16],
       [19, 13, 15, 16],
       [14, 11, 19, 14],
       [17, 11, 10, 17]])

In [3]:
import random

In [25]:
random.randint(1,6)

3

In [27]:
random.random()

0.3334563378758487

In [4]:
random.choice(['gta', 'residentn evil', 'olmpiya has fallen', 'unstoppbale', 'mario'])

'gta'

In [5]:
random.choices([ 'gta', 'residentn evil', 'olmpiya has fallen', 'unstoppbale', 'mario' ], k = 2 )

['olmpiya has fallen', 'unstoppbale']